from typing import Sequence

class DeviceInfo:
    num_qubits: int
    couplings: list[tuple[int, int]]

class NodeErrorRates:
    readout: float
    x: float
    reset: float
    sum_error: float

class EdgeErrorRates:
    cx: float

class TopologyGraph:
    def __init__(self, backend=None, noise_model=None) -> None: ...
    def rebuild(self) -> None: ...
    def qubits(self) -> list[int]: ...
    def has_qubit(self, q: int) -> bool: ...
    def node(self, q: int) -> NodeErrorRates: ...
    def directed_edges(self) -> list[tuple[int, int]]: ...
    def has_cx(self, q0: int, q1: int) -> bool: ...
    def edge(self, q0: int, q1: int) -> EdgeErrorRates: ...
    def to_networkx(self): ...

def sum_weights(weights: Sequence[float]) -> float: ...
def count_edges(device: DeviceInfo) -> int: ...

class CircuitOp:
    q0: int
    q1: int
    gate: str

class CircuitInfo:
    num_qubits: int
    ops: list[CircuitOp]

def circuit_from_qiskit(qc) -> CircuitInfo: ...

class TemporalGateEvents:
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_events(self) -> int: ...
    def timeline_len(self, qubit: int) -> int: ...
    def partner_timeline(self, qubit: int) -> list[int]: ...
    def partner_timeline_with_ids(self, qubit: int) -> list[tuple[int, int]]: ...
    def event_endpoints(self, event: int) -> tuple[int, int]: ...
    def event_multiplicity(self, event: int) -> int: ...
    def event_weight(self, event: int) -> float: ...
    def event_original_indices(self, event: int) -> list[int]: ...

class TemporalGraph:
    @property
    def num_nodes(self) -> int: ...
    @property
    def nnz(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def row_ptr(self) -> list[int]: ...
    @property
    def col_idx(self) -> list[int]: ...
    @property
    def node_weights(self) -> list[int]: ...
    @property
    def edge_weights(self) -> list[int]: ...
    def node(self, node: int) -> tuple[int, int, int]: ...
    def neighbors(self, node: int) -> tuple[list[int], list[int]]: ...

class ConnectivityGraph:
    @property
    def num_qubits(self) -> int: ...
    @property
    def nnz(self) -> int: ...
    @property
    def num_edge_ids(self) -> int: ...
    @property
    def node_weights(self) -> list[int]: ...
    def count(self, q: int, r: int) -> float: ...
    def edge_id(self, q: int, r: int) -> int: ...
    def edge_endpoints(self, edge_id: int) -> tuple[int, int]: ...
    def edge_original_indices(self, edge_id: int) -> list[int]: ...
    def edge_original_indices_by_qubits(self, q: int, r: int) -> list[int]: ...
    def neighbors(self, qubit: int) -> tuple[list[int], list[float]]: ...
    def neighbors_with_ids(self, qubit: int) -> tuple[list[int], list[float], list[int]]: ...

class CircuitGraph:
    def __init__(self, qc) -> None: ...
    def num_qubits(self) -> int: ...
    def num_gate_kinds(self) -> int: ...
    def gate_name(self, id: int) -> str: ...
    def oneq_counts(self) -> list[int]: ...
    def node_weights(self) -> list[int]: ...
    def ops(self) -> list[tuple[int, int, str]]: ...
    def ops_with_indices(self) -> list[tuple[int, int, int, str]]: ...
    def cut_edges(self, primary: Sequence[int], extra_block: Sequence[int] = ...) -> list[tuple[int, int, int, str]]: ...
    def cut_edge_indices(self, primary: Sequence[int], extra_block: Sequence[int] = ...) -> list[int]: ...
    def qubits(self) -> list[int]: ...
    @property
    def temporal_events(self) -> TemporalGateEvents: ...
    @property
    def temporal_graph(self) -> TemporalGraph: ...
    @property
    def connectivity(self) -> ConnectivityGraph: ...
    def count_temporal_cross_edges(self, common_qubit: int, set_a: Sequence[int], set_b: Sequence[int]) -> int: ...

def global_METIS_solver(
    graph: CircuitGraph,
    capacities: Sequence[int],
    imbalance: float = ...,
    seed: int = ...
) -> list[int]: ...

def global_temporal_METIS_solver(
    temporal_graph: TemporalGraph,
    capacities: Sequence[int],
    imbalance: float = ...,
    seed: int = ...
) -> list[int]: ...

def refine_partition(
    graph: CircuitGraph,
    capacities: Sequence[int],
    warm_start: Sequence[int] = ...,
    warm_start_extra_blocks: Sequence[Sequence[int]] = ...,
    max_passes: int = ...,
    enable_overlap: bool = ...,
    overlap_penalty: float = ...,
    cut_weight: int = ...,
    overlap_weight: int = ...,
    ged_weight: float = ...,
    parallel_ged: bool = ...,
    topology_graphs = ...,
    ged_callback = ...,
    overlap_local_callback = ...,
    use_tabu: bool = ...,
    tabu_tenure: int = ...,
    tabu_max_iters: int = ...,
    parallel_tabu: bool = ...,
    ged_balance: float = ...,
    ged_eval_interval: int = ...,
    ged_candidate_count: int = ...,
    optimize_hardware_placement: bool = ...,
    store_history: bool = ...,
    qap_use_routing: bool = ...,
) -> dict: ...
